from time import sleep
import sys

print("abc")
print("abc")
# sys.stdout.flush()
sleep(5)
# print(f"1: {input()}")
# sys.stdin.flush()
# sys.stdout.flush()
# print(f"2: {sys.stdin.read(1)}")
# print(f"2: {sys.stdin.read(1)}")
# print(f"2: {sys.stdin.read(1)}")
# print(f"2: {sys.stdin.read(1)}")
# print(f"2: {sys.stdin.read(1)}")
# print(f"2: {sys.stdin.read(1)}")
# print(f"2: {sys.stdin.read(1)}")
# print(f"2: {sys.stdin.read(1)}")
# print(f"2: {sys.stdin.read(1)}")
# print(f"3: {sys.stdin.read()}")
# sys.stdin.flush()
# sys.stdout.flush()
print("abc")
# sys.stdout.flush()
sys.exit(0)
